FROM node:16.13.2 as npm-build
ARG GITHUB_TOKEN  
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY .npmrc .npmrc  
COPY package.json package-lock.json ./
USER $user
RUN npm install
RUN rm -f .npmrc
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=npm-build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

